'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { recencyWeight, normalizeHistory, venueStats, currentStandings, expectedGoals, poisson, dixonColesTau, scoreMatrix, matrixMarkets, EloEngine, trainArtifact, h2h, fatigue, xgFeatures, playerImportance, assessAbsences, removeVig, shinProbabilities, analyzeMatch } = require('../probability-engine');

const kickoff = '2026-09-01T18:00:00Z';
function row(day, home='A', away='B', hg=1, ag=0, extra={}) { return { leagueId:39, home, away, home_score:hg, away_score:ag, home_ht:Math.min(hg,1), away_ht:Math.min(ag,1), playedAt:new Date(Date.UTC(2023,7,1+day)).toISOString(), ...extra }; }
function leagueHistory(count=240) { const teams=['A','B','C','D','E','F','G','H']; return Array.from({length:count},(_,i)=>{const home=teams[i%teams.length],away=teams[(i*3+1)%teams.length]===home?teams[(i+2)%teams.length]:teams[(i*3+1)%teams.length];return row(i*4,home,away,(i+home.charCodeAt(0))%4,(i*2+away.charCodeAt(0))%3);}); }

test('Poisson dağılımı 0-20 aralığında yaklaşık bire toplamlanır',()=>assert.ok(Math.abs(Array.from({length:21},(_,i)=>poisson(i,1.7)).reduce((a,b)=>a+b)-1)<1e-8));
test('0-10 skor matrisi normalize edilir',()=>{const matrix=scoreMatrix(1.6,1.1,-.07);assert.equal(matrix.length,11);assert.ok(Math.abs(matrix.flat().reduce((a,b)=>a+b)-1)<1e-12);});
test('1X2 toplamı birdir',()=>{const p=matrixMarkets(scoreMatrix(1.6,1.1),1.6,1.1);assert.ok(Math.abs(p.home+p.draw+p.away-1)<1e-12);});
test('Dixon-Coles yalnız düşük skor hücrelerini düzeltir',()=>{assert.notEqual(dixonColesTau(0,0,1.4,1.1,-.08),1);assert.equal(dixonColesTau(2,1,1.4,1.1,-.08),1);});
test('lambda lig ve iç/dış saha güçlerinden hesaplanır',()=>{const rows=[row(1,'A','C',2,0),row(2,'D','B',0,1),row(3,'A','D',3,1),row(4,'C','B',1,2),row(5,'A','E',1,0),row(6,'E','B',1,1)];const value=expectedGoals(normalizeHistory(rows,kickoff),'A','B',kickoff);assert.ok(value.home>0&&value.away>0);assert.ok(value.strengths.homeAttack>0);});
test('iç saha ve deplasman örnekleri karıştırılmaz',()=>{const rows=normalizeHistory([row(1,'A','B'),row(2,'B','A'),row(3,'A','C'),row(4,'C','A')],kickoff);assert.equal(venueStats(rows,'A','home',kickoff).played,2);assert.equal(venueStats(rows,'A','away',kickoff).played,2);});
test('güncellik ağırlığı 180 günde yarılanır',()=>assert.ok(Math.abs(recencyWeight(180)-.5)<1e-12));
test('H2H yalnız son iki yılı kullanır ve yoksa null döner',()=>{const rows=normalizeHistory([row(1),{...row(800),playedAt:'2026-08-01T12:00:00Z'}],kickoff);assert.equal(h2h(rows,'A','B',kickoff).played,1);assert.equal(h2h(rows,'X','Y',kickoff),null);});
test('eksik xG sıfıra dönüştürülmez',()=>{const [value]=normalizeHistory([row(1)],kickoff);assert.equal(value.homeXg,null);assert.equal(value.awayXg,null);});
test('eksik sakatlık istatistiği nötr ve doğrulanmamış kalır',()=>{assert.equal(playerImportance({name:'X'}).score,null);assert.equal(assessAbsences({home:[{name:'X'}],away:[]}).home[0].importance.verified,false);});
test('kritik oyuncu önem sınıflaması formülü izler',()=>{const value=playerImportance({minutesShare:1,startShare:1,goalContributionShare:1,assistContributionShare:1,ratingPercentile:1,positionCriticality:1,keyRoleIndicator:1});assert.equal(value.score,1);assert.equal(value.classification,'Çok kritik');});
test('puan durumu yalnız o ana kadarki sezon maçlarından oluşur',()=>{const table=currentStandings(normalizeHistory([{...row(760,'A','B',2,0),playedAt:'2026-08-01T12:00:00Z'},{...row(761,'B','C',1,1),playedAt:'2026-08-08T12:00:00Z'},{...row(762,'A','C',9,0),playedAt:'2026-09-02T12:00:00Z'}],kickoff),kickoff);assert.equal(table.find(x=>x.team==='A').points,3);});
test('fikstür yoğunluğu 7 ve 14 günlük pencereleri sayar',()=>{const rows=normalizeHistory([{...row(1),playedAt:'2026-08-29T12:00:00Z'},{...row(2,'C','A'),playedAt:'2026-08-20T12:00:00Z'}],kickoff);const value=fatigue(rows,'A',kickoff);assert.equal(value.matchesLast7Days,1);assert.equal(value.matchesLast14Days,2);});
test('Elo kronolojik işler ve gelecek maç sonucu önceki tahmine sızmaz',()=>{const engine=new EloEngine();const before=engine.predict('A','B');engine.process(normalizeHistory([row(2),row(1)],kickoff));assert.ok(engine.predict('A','B')[0]>before[0]);});
test('gelecek ve duplicate maçlar feature geçmişine girmez',()=>{const source=[row(1),row(1),{...row(2),playedAt:'2026-09-02T12:00:00Z'}];assert.equal(normalizeHistory(source,kickoff).length,1);});
test('walk-forward artifact kronolojik train-validation-test ayırır ve tam metrik üretir',()=>{const artifact=trainArtifact(normalizeHistory(leagueHistory(),kickoff));assert.equal(artifact.split.train+artifact.split.validation+artifact.split.test,240);assert.equal(artifact.calibration.fittedOn,'validation');assert.ok(artifact.metrics.samples>0);for(const key of ['logLoss','brier','rankedProbabilityScore','calibrationError','accuracy','drawPrecision','drawRecall','coverage'])assert.ok(key in artifact.metrics);assert.ok(artifact.metrics.legacy.samples>0);});
test('xG özellikleri kaynakları kontrolsüz birleştirmez',()=>{const rows=normalizeHistory([row(1,'A','B',1,0,{homeXg:1.2,awayXg:.4,source:'one'}),row(2,'A','C',2,1,{homeXg:1.8,awayXg:.8,source:'one'}),row(3,'A','D',0,0,{homeXg:4,awayXg:4,source:'two'})],kickoff);const value=xgFeatures(rows,'A','home',kickoff);assert.equal(value.source,'one');assert.equal(value.samples,2);});
test('vig temizleme ve Shin olasılıkları normalize edilir',()=>{assert.ok(Math.abs(removeVig(2,3.5,4).reduce((a,b)=>a+b)-1)<1e-12);assert.ok(Math.abs(shinProbabilities(2,3.5,4).reduce((a,b)=>a+b)-1)<1e-12);});
test('eski oran snapshotı value hesabında reddedilir',()=>{const result=analyzeMatch({match:{home:'A',away:'B',kickoffUtc:kickoff,status:'SCHEDULED'},rows:leagueHistory(),odds:{home:2,draw:3.5,away:4,capturedAt:'2026-09-02T00:00:00Z'}});assert.equal(result.value,null);});
test('zaman damgası olmayan oran snapshotı value hesabında reddedilir',()=>{const result=analyzeMatch({match:{home:'A',away:'B',kickoffUtc:kickoff,status:'SCHEDULED'},rows:leagueHistory(),odds:{home:2,draw:3.5,away:4}});assert.equal(result.value,null);});
test('gerçekten yetersiz veride VERİ YETERSİZ kullanılır',()=>{const value=analyzeMatch({match:{home:'A',away:'B',kickoffUtc:kickoff,status:'SCHEDULED'},rows:[row(1)]});assert.equal(value.decision,'VERİ YETERSİZ');assert.equal(value.primarySelection,undefined);});
test('dengeli ve yeterli verili maçta en güçlü seçenek üretilir',()=>{const value=analyzeMatch({match:{home:'A',away:'B',kickoffUtc:kickoff,status:'SCHEDULED'},rows:leagueHistory()});assert.notEqual(value.decision,'VERİ YETERSİZ');assert.ok(value.primarySelection);assert.ok(value.primarySelection.probability>=value.alternativeSelections[0].probability);assert.equal(value.usedMatches.total,20);});
test('1X2 ve ters ikili pazarlar yuvarlama payıyla yüzde 100 eder',()=>{const p=analyzeMatch({match:{home:'A',away:'B',kickoffUtc:kickoff,status:'SCHEDULED'},rows:leagueHistory()}).probabilities;assert.ok(Math.abs(p.home+p.draw+p.away-100)<=.2);assert.ok(Math.abs(p.over25+p.under25-100)<=.1);assert.ok(Math.abs(p.bttsYes+p.bttsNo-100)<=.1);});
test('masaüstü sağlayıcıları production motorunu kullanır ve paket motoru içerir',()=>{const international=fs.readFileSync(path.join(__dirname,'..','international-analysis-provider.js'),'utf8');const free=fs.readFileSync(path.join(__dirname,'..','free-provider.js'),'utf8');const pkg=require('../package.json');assert.match(international,/runProbabilityEngine/);assert.match(free,/runProbabilityEngine/);assert.ok(pkg.build.files.includes('probability-engine.js'));});
