function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,Math.round(n)))}
function makeRecommendation({scores,home,away,h2h,injuriesAvailable=true}){const picks=[],avoid=[],warnings=[],add=(market,confidence,reason)=>picks.push({market,confidence:clamp(confidence),risk:confidence>=72?'Orta':confidence>=60?'Orta-yüksek':'Yüksek',reason});if(scores.homeAdvantage>=58)add('1X (ev sahibi kaybetmez)',scores.homeAdvantage,`Ev avantajı %${scores.homeAdvantage}; deplasman ekibi son örnekte ${away.losses} yenilgi aldı.`);if(scores.homeAdvantage>=68)add('Maç sonucu 1',scores.homeAdvantage-4,'Ev sahibi yönü güçlü; 1X daha güvenli.');if(scores.homeAdvantage<=42)add('X2 (deplasman kaybetmez)',100-scores.homeAdvantage,`Deplasman yönü %${100-scores.homeAdvantage} avantajlı.`);if(scores.homeAdvantage<=32)add('Maç sonucu 2',96-scores.homeAdvantage,'Deplasman yönü güçlü; X2 daha güvenli.');if(scores.over25>=62)add('2,5 Üst',scores.over25,`Gol eğilimi %${scores.over25}.`);else if(scores.over25<=48)add('3,5 Alt',clamp(68-scores.over25/3),`2,5 Üst yalnızca %${scores.over25}; geniş alt sınırı tercih edildi.`);if(scores.btts>=62)add('KG Var',scores.btts,`Karşılıklı gol eğilimi %${scores.btts}.`);else if(scores.btts<=38)add('KG Yok',100-scores.btts,`Karşılıklı gol eğilimi yalnızca %${scores.btts}.`);if(scores.firstHalf>=62)add('İlk yarı 0,5 Üst',scores.firstHalf,`İlk yarı gol göstergesi %${scores.firstHalf}.`);if(scores.secondHalf>=62)add('İkinci yarı 0,5 Üst',scores.secondHalf,`İkinci yarı gol göstergesi %${scores.secondHalf}.`);if(scores.over25>48&&scores.over25<62)avoid.push('2,5 gol pazarı: güçlü yön yok');if(scores.btts>38&&scores.btts<62)avoid.push('KG Var/Yok: güçlü yön yok');if(h2h.played<4)warnings.push(`İkili rekabet örneği yalnızca ${h2h.played} maç.`);if(!injuriesAvailable)warnings.push('Sakat/cezalı, hakem ve kesin kadro verisi doğrulanamadı.');warnings.push('Kadrolar açıklandıktan sonra analizi yenile.');const ranked=picks.sort((a,b)=>b.confidence-a.confidence),strong=ranked.filter(p=>p.confidence>=60),primary=strong[0]||null;return{action:primary?'SEÇENEKLERİ DEĞERLENDİR':'PAS GEÇ',primary,picks:ranked.slice(0,4),avoid,warnings,risk:primary?primary.risk:'Yüksek',stake:primary?(primary.confidence>=72?'Toplam en fazla 1 birim':'Toplam en fazla 0,5 birim'):'0 birim',comboWarning:ranked.length>1?'Aynı maça ait seçimleri tek kuponda birleştirmek riski katlar; alternatif olarak değerlendir.':null}}
function avg(v){v=v.filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:0}
function side(f,id){return f.teams.home.id===id?'home':'away'}
function scored(f,id){return Number(f.goals[side(f,id)]||0)}
function conceded(f,id){return Number(f.goals[side(f,id)==='home'?'away':'home']||0)}
function result(f,id){const s=scored(f,id),c=conceded(f,id);return s>c?'W':s<c?'L':'D'}
function summarizeTeam(fixtures,id,venue){const finished=fixtures.filter(f=>f.fixture.status.short==='FT');const filtered=finished.filter(f=>side(f,id)===venue);const rows=(filtered.length>=3?filtered:finished).slice(0,10);const gf=rows.map(f=>scored(f,id)),ga=rows.map(f=>conceded(f,id));const fh=rows.map(f=>Number(f.score.halftime?.[side(f,id)]||0));const sh=gf.map((x,i)=>Math.max(0,x-fh[i]));const pts=rows.map(f=>({W:3,D:1,L:0})[result(f,id)]);return{played:rows.length,wins:pts.filter(x=>x===3).length,draws:pts.filter(x=>x===1).length,losses:pts.filter(x=>x===0).length,points:pts.reduce((a,b)=>a+b,0),goalsForAvg:+avg(gf).toFixed(2),goalsAgainstAvg:+avg(ga).toFixed(2),firstHalfAvg:+avg(fh).toFixed(2),secondHalfAvg:+avg(sh).toFixed(2),over25:rows.length?clamp(rows.filter((f,i)=>gf[i]+ga[i]>2).length/rows.length*100):0,btts:rows.length?clamp(rows.filter((f,i)=>gf[i]>0&&ga[i]>0).length/rows.length*100):0,form:rows.map(f=>result(f,id)).join('')}}
function summarizeH2H(rows,hid,aid){rows=rows.filter(f=>f.fixture.status.short==='FT');let hw=0,aw=0,d=0;for(const f of rows){const hg=Number(f.goals.home||0),ag=Number(f.goals.away||0);if(hg===ag)d++;else(hg>ag?f.teams.home.id:f.teams.away.id)===hid?hw++:aw++}return{played:rows.length,homeWins:hw,draws:d,awayWins:aw,goalsAvg:+avg(rows.map(f=>Number(f.goals.home||0)+Number(f.goals.away||0))).toFixed(2),over25:rows.length?clamp(rows.filter(f=>Number(f.goals.home||0)+Number(f.goals.away||0)>2).length/rows.length*100):0}}
function summarizePlayers(responses,id){const map=new Map;for(const response of responses)for(const team of response.response||[])if(team.team.id===id)for(const p of team.players||[]){const s=p.statistics?.[0]||{},o=map.get(p.player.id)||{name:p.player.name,r:[],minutes:0,goals:0,assists:0,appearances:0};o.appearances++;o.minutes+=Number(s.games?.minutes||0);if(Number(s.games?.rating))o.r.push(Number(s.games.rating));o.goals+=Number(s.goals?.total||0);o.assists+=Number(s.goals?.assists||0);map.set(p.player.id,o)}return[...map.values()].map(x=>({name:x.name,rating:+avg(x.r).toFixed(2),minutes:x.minutes,goals:x.goals,assists:x.assists,appearances:x.appearances})).sort((a,b)=>b.rating-a.rating||b.minutes-a.minutes).slice(0,8)}
function refereeHistory(rows,ref,id){if(!ref)return{referee:'Henüz atanmadı',matches:0,wins:0,draws:0,losses:0};rows=rows.filter(f=>(f.fixture.referee||'').toLowerCase()===ref.toLowerCase());return{referee:ref,matches:rows.length,wins:rows.filter(f=>result(f,id)==='W').length,draws:rows.filter(f=>result(f,id)==='D').length,losses:rows.filter(f=>result(f,id)==='L').length}}
function buildAnalysis(x){const hid=x.fixture.teams.home.id,aid=x.fixture.teams.away.id,home=summarizeTeam(x.homeFixtures,hid,'home'),away=summarizeTeam(x.awayFixtures,aid,'away'),h2h=summarizeH2H(x.h2h,hid,aid);const injuries={home:x.injuries.filter(i=>i.team.id===hid).map(i=>({name:i.player.name,type:i.player.type,reason:i.player.reason})),away:x.injuries.filter(i=>i.team.id===aid).map(i=>({name:i.player.name,type:i.player.type,reason:i.player.reason}))};const homeAdvantage=clamp(50+(home.points/Math.max(home.played,1)-away.points/Math.max(away.played,1))*10+(home.goalsForAvg-away.goalsAgainstAvg)*8-injuries.home.length*2+injuries.away.length*2);return{home,away,h2h,injuries,players:{home:x.homePlayers,away:x.awayPlayers},referee:{home:refereeHistory(x.homeFixtures,x.fixture.fixture.referee,hid),away:refereeHistory(x.awayFixtures,x.fixture.fixture.referee,aid)},scores:{homeAdvantage,over25:clamp(avg([home.over25,away.over25,h2h.over25])),btts:clamp(avg([home.btts,away.btts])),firstHalf:clamp((home.firstHalfAvg+away.firstHalfAvg)/2/1.4*100),secondHalf:clamp((home.secondHalfAvg+away.secondHalfAvg)/2/1.6*100),confidence:clamp(45+Math.min(home.played+away.played,20)*1.5+Math.min(h2h.played,10),35,88)},generatedAt:new Date().toISOString()}}
module.exports={buildAnalysis,summarizeTeam,summarizeH2H,summarizePlayers,makeRecommendation,clamp};
