type Quote = { bookmaker: string; odds: number; is_highest: boolean; is_lowest: boolean };
type Selection = { name: string; average_odds: number; median_odds: number; min_odds: number; max_odds: number; bookmaker_count: number; normalized_probability: number | null; quotes: Quote[] };
type Market = { key: string; point: number | null; margin: number | null; selections: Selection[] };
type Data = { provider?: string; updated_at?: string; bookmaker_count?: number; markets?: Market[]; consensus?: { favorite: string; strength: string; favorite_bookmakers: number; bookmaker_count: number; probabilities: { selection: string; probability: number }[] } | null; betting_splits?: { selection: string; tickets: number | null; money: number | null }[]; movements?: { bookmaker: string; market: string; selection: string; opening_odds: number; current_odds: number; change_percent: number; classification: string }[]; steam_move?: { bookmaker_count: number; market: string; selection: string } | null; warning?: string; disclaimer?: string };

const pct = (value: number | null | undefined) => value == null ? "—" : `${(value * 100).toFixed(1)}%`;
const marketNames: Record<string, string> = { h2h: "1X2 Maç Sonucu", h2h_3_way: "1X2 Maç Sonucu", draw_no_bet: "Beraberlikte İade", totals: "Toplam Gol", alternate_totals: "Toplam Gol (Tüm Çizgiler)", btts: "Karşılıklı Gol", spreads: "Handikap", alternate_spreads: "Asya / Alternatif Handikap", team_totals: "Takım Golü", alternate_team_totals: "Takım Golü (Tüm Çizgiler)", h2h_h1: "İlk Yarı 1X2", totals_h1: "İlk Yarı Alt/Üst", btts_h1: "İlk Yarı KG" };

export default function GlobalBetting({ data }: { data: Data | null }) {
  if (!data) return <section className="panel"><h2>Global Bahis</h2><p>Bahis piyasası servisine ulaşılamadı.</p></section>;
  const markets = data.markets ?? [];
  return <section className="betting-module">
    <div className="source-strip"><b>Kaynak: {data.provider ?? "—"}</b><span>Son güncelleme: {data.updated_at ? new Intl.DateTimeFormat("tr-TR", { dateStyle: "short", timeStyle: "short" }).format(new Date(data.updated_at)) : "—"}</span><span>{data.bookmaker_count ?? 0} bookmaker</span></div>
    {data.warning && <div className="availability">{data.warning}</div>}
    <div className="panel"><h2>Avrupa Piyasa Konsensüsü</h2>{data.consensus ? <><div className="consensus"><strong>{data.consensus.favorite}</strong><span>Güç: {data.consensus.strength}</span><span>{data.consensus.favorite_bookmakers} / {data.consensus.bookmaker_count} bookmaker favori görüyor</span></div><div className="probabilities">{data.consensus.probabilities.map(p => <div key={p.selection}><small>{p.selection}</small><strong>{pct(p.probability)}</strong></div>)}</div></> : <p>1X2 konsensüs verisi bu maç için mevcut değil.</p>}</div>
    <div className="admin-grid"><div className="panel"><h2>Public Betting</h2>{data.betting_splits?.length ? data.betting_splits.map(s => <p key={s.selection}>{s.selection}: {s.tickets == null ? "Kupon verisi yok" : pct(s.tickets / 100)}</p>) : <p>Public betting verisi bu sağlayıcıda mevcut değil.</p>}</div><div className="panel"><h2>Money Percentage</h2>{data.betting_splits?.length ? data.betting_splits.map(s => <p key={s.selection}>{s.selection}: {s.money == null ? "Para verisi yok" : pct(s.money / 100)}</p>) : <p>Money percentage verisi bu sağlayıcıda mevcut değil.</p>}</div></div>
    <div className="panel"><h2>Oran Hareketleri</h2>{data.movements?.length ? data.movements.map((m, i) => <div className="movement" key={`${m.bookmaker}-${m.market}-${m.selection}-${i}`}><b>{m.bookmaker}</b> {m.selection}: {m.opening_odds.toFixed(2)} → {m.current_odds.toFixed(2)} <span>{m.change_percent > 0 ? "↑" : "↓"} %{Math.abs(m.change_percent).toFixed(1)} · {m.classification}</span></div>) : <p>Henüz birden fazla snapshot bulunmadığı için historical odds hareketi hesaplanamadı.</p>}{data.steam_move && <div className="signal">Piyasa hareketi tespit edildi: {data.steam_move.bookmaker_count} bookmaker, {data.steam_move.selection}.</div>}</div>
    {markets.map((market, index) => <details className="market-panel" open={index < 3} key={`${market.key}-${market.point}`}><summary>{marketNames[market.key] ?? market.key}{market.point != null ? ` · ${market.point}` : ""}<small>Marj: {pct(market.margin)}</small></summary>{market.selections.map(selection => <div className="selection-block" key={selection.name}><div className="selection-summary"><b>{selection.name}</b><span>Ort. {selection.average_odds.toFixed(2)}</span><span>Median {selection.median_odds.toFixed(2)}</span><span>Piyasa {pct(selection.normalized_probability)}</span><span>{selection.bookmaker_count} şirket</span></div><div className="odds-table"><div className="odds-head"><b>Bookmaker</b><b>Oran</b></div>{selection.quotes.map(q => <div key={q.bookmaker}><span>{q.bookmaker}</span><strong className={q.is_highest ? "high" : q.is_lowest ? "low" : ""}>{q.odds.toFixed(2)}</strong></div>)}</div></div>)}</details>)}
    {!markets.length && <div className="empty">Bu maç için global bookmaker oranı bulunamadı.</div>}
    <p className="disclaimer">{data.disclaimer}</p>
  </section>;
}
